services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest 
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Taipei
      - N8N_RUNNERS_ENABLED=true
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${ADMIN}
      - N8N_BASIC_AUTH_PASSWORD=${PASSWORD}
      - N8N_API_ALLOW_READ=true
      - N8N_API_ALLOW_WRITE=true
      - N8N_PORT=5678
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: unless-stopped